### ISSUE TITLE
Solve aditional check payment in test mode

### ISSUE THREAD

**Issue by trejjam** [contributte/thepay#2]
In test mode is problem with non persist payment into ThePay database:

> metody getPayment a getPaymentState vrací výsledek jen pro platbu, která existuje v platební bráně a patří příslušnému obchdoníkovi a účtu. Testovací platební brána vrací náhodné paymentId a neukládá platby do databáze. Pro testování API na testovací bráně lze použít paymentId cca do padesátky, které v testovací bráně existují. V ostrém provozu pak použijete paymentId které dostanete od brány.

**Comment by f3l1x** [comment]
What about this @trejjam?

**Comment by trejjam** [comment]
I do not think it is solvable in any other way than it is done in [playground/thepay](https://github.com/contributte/playground/blob/master/thepay/app/Presenters/HomepagePresenter.php#L77), cause server API did not change much since.

Closing
