### ISSUE TITLE
Neprojde validace provedené test platby,  při použití demo účtu

### ISSUE THREAD

**Issue by mikethejet** [contributte/thepay#39]
try {
			if ($returnedPayment->verifySignature()) {
				if (in_array($returnedPayment->getStatus(), [
					ReturnedPayment::STATUS_OK,
					ReturnedPayment::STATUS_WAITING,
				], TRUE)) { .. .

verifySignature.. vrací vyjímku protože:

nastavení pro demo vychází z konfigu ? 
z jakého ?

Brána pro demo vrací: 
merchantId = 1 
accountID = 3
-- 
Defaultně pro demo v configu uvedeno
merchantId = 1 
accountID = 1 

Selže pak verify Signature..
Jak nastavit parametry pro demo?
Zatím jsem to řešil přímým nastavením v 

$returnedPayment = $this->tpReturnedPayment->create( $config_demo );

**Comment by trejjam** [comment]
Hi,
the project has a [documentation](https://github.com/contributte/thepay/tree/master/.docs). Please take a look.

Otherwise, please provide the exception. Or any error details.
Thank you
